apiVersion: v1
kind: Namespace
metadata:
  name: elk
  labels:
    name: elk

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: elk-ingress
  namespace: kube-system
  labels:
    app: elk-ingress
    group: elk
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: kibana.local.io
      http:
        paths:
          - path: /
            backend:
              serviceName: kibana-logging
              servicePort: 5601
    - host: elasticsearch.local.io
      http:
        paths:
          - path: /
            backend:
              serviceName: elasticsearch
              servicePort: 9200
